name: GoonRush
main: com.skillplugins.advancedmlgrush.MLGRush
version: 1.0.0
author: FuneralFlower
website: https://skillplugins.com
softdepend: [ PlaceholderAPI, ProtocolLib ]
commands:
  goonrush:
  setspawn:
  setupmap:
    aliases:
      - setupmaptemplate
      - setuptemplate
      - createmap
      - setup
  quit:
    aliases:
      - leave
      - l
  queue:
  settings:
  spectate:
  perks:
    aliases:
      - gadgets
  stats:
  statsreset:
    aliases:
      - resetstats
      - reset
      - clearstats
  sudo:
